version: "3"
services:
  backend:
    build: .
    environment:
      PORT: 80
      MONGO_HOST: db
      MONGO_PORT: 27017
    links:
    - "db:DB"
    ports:
    - "8080:80"
  db:
    image: mongo:latest
    ports:
    - "27017"

